# Generated by Django 6.0.3 on 2026-03-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('guest_phone', models.CharField(blank=True, max_length=20)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - በመጠባበቅ ላይ'), ('confirmed', 'Confirmed - ተረጋግጧል'), ('processing', 'Processing - በሂደት ላይ'), ('shipped', 'Shipped - ተልኳል'), ('delivered', 'Delivered - ደርሷል'), ('cancelled', 'Cancelled - ተሰርዟል')], default='pending', max_length=20)),
                ('shipping_address', models.TextField()),
                ('shipping_city', models.CharField(max_length=100)),
                ('preferred_contact', models.CharField(choices=[('phone', 'Phone - ስልክ'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('imo', 'Imo')], default='phone', max_length=20)),
                ('contact_number', models.CharField(max_length=20)),
                ('payment_method', models.CharField(choices=[('telebirr', 'TeleBirr'), ('cbe', 'CBE Birr'), ('bank_transfer', 'Bank Transfer'), ('western_union', 'Western Union'), ('paypal', 'PayPal'), ('cash', 'Cash on Delivery')], default='telebirr', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_teaching_order', models.BooleanField(default=False)),
                ('is_group_discount', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipping_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shippingcountry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
