# Generated by Django 6.0.3 on 2026-03-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('order', 'Order Question'), ('class', 'Class Question'), ('feedback', 'Feedback'), ('other', 'Other')], default='general', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('telebirr', 'TeleBirr'), ('cbe', 'CBE Birr'), ('bank_transfer', 'Bank Transfer'), ('western_union', 'Western Union'), ('paypal', 'PayPal'), ('cash', 'Cash on Delivery'), ('credit_card', 'Credit Card')], default='credit_card', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='preferred_contact',
            field=models.CharField(choices=[('phone', 'Phone - ስልክ'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending - በመጠባበቅ ላይ'), ('confirmed', 'Confirmed - ተረጋግጧል'), ('processing', 'Processing - በሂደት ላይ'), ('shipped', 'Shipped - ተልኳል'), ('delivered', 'Delivered - ደርሷል'), ('cancelled', 'Cancelled - ተሰርዟል')], default='confirmed', max_length=20),
        ),
    ]
