# Generated by Django 6.0.3 on 2026-03-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_contactmessage_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_last4',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('telebirr', 'TeleBirr'), ('cbe', 'CBE Birr'), ('bank_transfer', 'Bank Transfer'), ('western_union', 'Western Union'), ('paypal', 'PayPal'), ('cash', 'Cash on Delivery'), ('credit_card', 'Credit Card')], default='telebirr', max_length=20),
        ),
    ]
