# Generated by Django 6.0.3 on 2026-03-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_payment_last4_order_payment_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=100)),
                ('course_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('schedule', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=50)),
                ('payment_method', models.CharField(default='telebirr', max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending - በመጠባበቅ ላይ'), ('active', 'Active - ንቁ'), ('completed', 'Completed - ተጠናቋል'), ('cancelled', 'Cancelled - ተሰርዟል')], default='pending', max_length=20)),
                ('enroll_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-enroll_date'],
            },
        ),
    ]
