# Generated by Django 6.0.3 on 2026-03-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_amharic', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_amharic', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('instrument_type', models.CharField(choices=[('begena', 'በገና (Begena)'), ('kirar', 'ክራር (Kirar)'), ('masenqo', 'መሰንቆ (Masenqo)'), ('kebero', 'ከበሮ (Kebero)'), ('netela', 'ነጠላ (Netela)'), ('other', 'Other')], max_length=20)),
                ('service_type', models.CharField(choices=[('sell', 'For Sale - ለሽያጭ'), ('teach', 'For Teaching - ለስልጠና'), ('both', 'Both - ሁለቱም')], default='sell', max_length=10)),
                ('description', models.TextField()),
                ('description_amharic', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_currency', models.CharField(default='ETB', max_length=3)),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('delivery_days_min', models.PositiveIntegerField(default=5)),
                ('delivery_days_max', models.PositiveIntegerField(default=10)),
                ('ships_internationally', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('is_primary', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
        ),
    ]
