# Generated by Django 6.0.3 on 2026-03-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('domestic', 'Domestic - ሀገር ውስጥ'), ('east_africa', 'East Africa'), ('middle_east', 'Middle East'), ('europe', 'Europe'), ('north_america', 'North America'), ('oceania', 'Oceania')], max_length=20)),
                ('base_shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days_min', models.PositiveIntegerField(default=5)),
                ('estimated_days_max', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('additional_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='shipping.shippingzone')),
            ],
            options={
                'verbose_name_plural': 'Shipping Countries',
                'ordering': ['name'],
            },
        ),
    ]
